### ISSUE TITLE
Blog Post for How I Work

### ISSUE THREAD

**Issue by yurpcraft** [adbertram/HowIWorkIT#4]
Hey Adam!  I figured I'd shoot you an issue rather than potentially mucking up a pull request, so here you go.  The site is definitely a work in progress, but enjoy!

Name: Bryce McDonald
Title: Solutions Engineer
Link:  [How I Work IT](http://www.brycematthew.net/how/i/work/2016/11/30/how-I-work.html)
Twitter: [@_brycemcdonald](https://twitter.com/_brycemcdonald)

**Comment by adbertram** [comment]
Awesome! Thanks!
